### PR TITLE
Dwdd links

### PR DESCRIPTION
**Pull request by mwigham**
Added links back to the Media Suite to the DWDD data story.

Test plan:
- [x] check out branch
- [x] run locally and click on the links to the Media Suite in the NL and EN versions of the DWDD story
- [x] check that the correct query is opened in the Media Suite

### CODE REVIEW

**Review by phivk — COMMENTED** [review]
both location links point to the same query. my initial reaction is: why? 
As an insider I might realise that a split between NL and World has been made later during analysis. this is unclear as a reader.

**Comment by phivk** [comment]
re locations: I am not sure how this view tells me anything... 
I'm instructed to see "Location discussed", but can't tell the difference between "Segment" and "Program"
also, the locations seem to be not sorted by frequency, so I gain little information from these panels. (option for manual sorting is hidden and difficult to find, even if I'd come up with the idea to sort be frequency)

7B4AEF87-35CD-412E-9322-74A017BFF01A-661-000011598F7786C2

**Comment by phivk** [comment]
similar re program vs segment & sorting  for subjects:
B158929D-23BF-484C-8C27-D1EE1BE23C87-661-000011F4DCB58265

**Comment by phivk** [comment]
link in figure 5 requires login, would be good to announce that near the link.

**Comment by phivk** [comment]
I've made two commits:  dda31b8 and 65cc961 to the EN version. 
If you think it's an improvement you can apply these edits to the NL version too

**Comment by phivk** [comment]
a quick and dirty idea to give more visual attention to the first link:

7603C80D-464C-4476-8E7B-155DF474DCB5-661-000013A2DCE08A6D

could be applied to other links too:
B4F6B9A5-7562-4071-AA9F-8D08ECF317C8-661-000013F1E9ADAFA4

let me know what you think of this and I can commit and push :)

**Comment by phivk** [comment]
btw, I have merged the `corona` branch into `master`, as I should have done before...

**Comment by mwigham** [comment]
@phivk thanks for the review.

- both location links point to the same view: yes, this is true, and it is indeed because the filtering was done by hand. Any thoughts on how we could concisely explain this?
- location sorting will be available once the next release of the Media Suite is done, this is already in the query but the UI doesn't yet pick it up
- locations are annotated separately per programme and per segment (clip). I can change the name to clip. Explaining the situation is a bit complex for in the text relating to the link, I think
- login for Figure 5: I can repeat here that the metadata is available without a login but login is required to view the content
- icons for the links: yes, please commit and push!

I will copy your changes to the NL version

**Comment by phivk** [comment]
> 1. both location links point to the same view: yes, this is true, and it is indeed because the filtering was done by hand. Any thoughts on how we could concisely explain this?

we could say: 
- (under the global map): "see all locations"
- (under the NL map): "see all locations (including global)"

> 2. location sorting will be available once the next release of the Media Suite is done, this is already in the query but the UI doesn't yet pick it up
> 3. locations are annotated separately per programme and per segment (clip). I can change the name to clip. Explaining the situation is a bit complex for in the text relating to the link, I think

We could say: 

(scroll down to see 'Location discussed' per Program or Segment on the lefthand side, you can sort by frequency via the facet menu)

> 4. login for Figure 5: I can repeat here that the metadata is available without a login but login is required to view the content

aaaah! with the new instructions I am able to find the word cloud! would be good to be able to load this view straight away (like the facet sorting in the next release?), currently the first thing you see is a scary red notification that tells me I should log in to see content.

BTW: is it "word cloud" or "wordcloud"? current both are in use...

> 5. icons for the links: yes, please commit and push!

OK!

6. something I forgot: I think the links should open in a new tab. I will push an update.

**Comment by phivk** [comment]
@mwigham I've just pushed 2 updates, if you can do something with my feedback points above I consider this ready to be merged 👍

**Comment by mwigham** [comment]
@Philo van Kemenade <pvkemenade@beeldengeluid.nl> I've made changes and
pushed them

Op di 13 okt. 2020 om 12:19 schreef Philo van Kemenade <
notifications@github.com>:

**Review by phivk — APPROVED** [review]

**Pull request merged**
